.TH PIPEWALKER 6 2020-06-11 "Pipewalker" "Pipewalker Manual"
.SH NAME
pipewalker \- combination puzzle game
.SH SYNOPSIS
pipewalker [\fIOPTIONS\fR]...
.SH DESCRIPTION
.B pipewalker
is a puzzle game in which you need to combine the components into a single
circuit: connect all computers to a network server, bring water to the taps,
etc.
.SH OPTIONS
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message and exit.
.IP "\fB\-v\fR, \fB\-\-version\fR"
Display version information and exit.
.IP "\fB\-i\fR, \fB\-\-id\fR\fB=\fR\fIID\fR:"
Start the level with the specified ID (a number from 1 up to 99999999).
.IP "\fB\-c\fR, \fB\-\-width\fR\fB=\fR\fICOLUMNS\fR:"
Set level width (a number from 10 to 50).
.IP "\fB\-r\fR, \fB\-\-height\fR\fB=\fR\fIROWS\fR:"
Set level height (a number from 10 to 50).
.IP "\fB\-w\fR, \fB\-\-no\-wrap\fR"
Disable wrap mode.
.IP "\fB\-s\fR, \fB\-\-no\-sound\fR"
Disable sound.
.SH FILES
.I /usr/share/games/pipewalker/
.PP
.RS
Data directory for \fBpipewalker\fR themes.
.SH NOTES
.B pipewalker
supports various themes.
Themes are stored as a set of textures in a PNG file. All themes must be
1024x896 pixels in size.
To add a new theme, copy the PNG file to the \fI/usr/share/games/pipewalker\fR
data directory.  The file name is used as the theme name.
.SH EXAMPLE
To start pipewalker on the level 1234, with wrap mode disabled, and level
map 10x20:
.PP
.RS
.B $ pipewalker \-\-id=1234 \-\-no\-wrap \-\-width=10 \-\-height=20
.RE
.SH AUTHORS
This manual page was written by David da Silva Polverari
<david.polverari@gmail.com> for the Debian project (but may be used by others).
